name: Pub Score Checker
on:
  pull_request:
    branches:
    - "main"

jobs:

  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          echo Score is: $TOTAL
          if (( $TOTAL < 120 ))
          then
            echo Pub Score too low.
            exit 1
          fi
